-- Matugen Neovim colorscheme
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.o.termguicolors = true
vim.g.colors_name = "matugen"

local colors = {
  bg = "#1f0f0b",
  bg_dark = "#2d1b17",
  bg_light = "#392521",
  fg = "#fddbd4",
  fg_dark = "#e7bdb4",
  primary = "#ffb4a3",
  secondary = "#ffb4a3",
  tertiary = "#aec6ff",
  error = "#ffb4ab",
  outline = "#ad8880",
  primary_container = "#ff5630",
  on_primary_container = "#000000",
  secondary_container = "#8b230a",
  on_secondary_container = "#ffdcd5",
  tertiary_container = "#508eff",
  on_tertiary_container = "#000000",
  error_container = "#93000a",
  on_error_container = "#ffdad6",
}

local highlights = {
  Normal = { fg = colors.fg, bg = "NONE" }, -- Transparent bg
  NormalFloat = { fg = colors.fg, bg = colors.bg_dark },
  Comment = { fg = colors.outline, italic = true },
  Constant = { fg = colors.tertiary },
  String = { fg = colors.secondary },
  Character = { fg = colors.secondary },
  Number = { fg = colors.tertiary },
  Boolean = { fg = colors.tertiary },
  Float = { fg = colors.tertiary },
  Identifier = { fg = colors.primary },
  Function = { fg = colors.primary },
  Statement = { fg = colors.primary, bold = true },
  Conditional = { fg = colors.primary, bold = true },
  Repeat = { fg = colors.primary, bold = true },
  Label = { fg = colors.primary },
  Operator = { fg = colors.fg },
  Keyword = { fg = colors.primary, bold = true },
  Exception = { fg = colors.error },
  PreProc = { fg = colors.secondary },
  Include = { fg = colors.secondary },
  Define = { fg = colors.secondary },
  Macro = { fg = colors.secondary },
  PreCondit = { fg = colors.secondary },
  Type = { fg = colors.tertiary },
  StorageClass = { fg = colors.tertiary },
  Structure = { fg = colors.tertiary },
  Typedef = { fg = colors.tertiary },
  Special = { fg = colors.secondary },
  SpecialChar = { fg = colors.secondary },
  Tag = { fg = colors.secondary },
  Delimiter = { fg = colors.fg },
  SpecialComment = { fg = colors.outline, italic = true },
  Debug = { fg = colors.error },
  Underlined = { underline = true },
  Ignore = { fg = colors.outline },
  Error = { fg = colors.error, bold = true },
  Todo = { fg = colors.bg, bg = colors.primary, bold = true },

  ColorColumn = { bg = colors.bg_light },
  Conceal = { fg = colors.outline },
  Cursor = { fg = colors.bg, bg = colors.fg },
  CursorColumn = { bg = colors.bg_light },
  CursorLine = { bg = colors.bg_light },
  Directory = { fg = colors.primary },
  DiffAdd = { fg = colors.secondary_container, bg = colors.on_secondary_container },
  DiffChange = { fg = colors.tertiary_container, bg = colors.on_tertiary_container },
  DiffDelete = { fg = colors.error_container, bg = colors.on_error_container },
  DiffText = { fg = colors.primary_container, bg = colors.on_primary_container },
  EndOfBuffer = { fg = colors.bg },
  ErrorMsg = { fg = colors.error },
  VertSplit = { fg = colors.outline },
  Folded = { fg = colors.fg_dark, bg = colors.bg_dark },
  FoldColumn = { fg = colors.fg_dark, bg = "NONE" },
  SignColumn = { fg = colors.fg_dark, bg = "NONE" },
  IncSearch = { fg = colors.bg, bg = colors.primary },
  LineNr = { fg = colors.outline },
  CursorLineNr = { fg = colors.primary, bold = true },
  MatchParen = { fg = colors.tertiary, bold = true },
  ModeMsg = { fg = colors.primary, bold = true },
  MoreMsg = { fg = colors.primary },
  NonText = { fg = colors.outline },
  Pmenu = { fg = colors.fg, bg = colors.bg_dark },
  PmenuSel = { fg = colors.bg, bg = colors.primary },
  PmenuSbar = { bg = colors.bg_dark },
  PmenuThumb = { bg = colors.outline },
  Question = { fg = colors.primary },
  Search = { fg = colors.bg, bg = colors.secondary },
  SpecialKey = { fg = colors.outline },
  SpellBad = { sp = colors.error, undercurl = true },
  SpellCap = { sp = colors.tertiary, undercurl = true },
  SpellLocal = { sp = colors.primary, undercurl = true },
  SpellRare = { sp = colors.secondary, undercurl = true },
  StatusLine = { fg = colors.fg, bg = colors.bg_dark },
  StatusLineNC = { fg = colors.fg_dark, bg = "NONE" },
  TabLine = { fg = colors.fg_dark, bg = colors.bg_dark },
  TabLineFill = { bg = "NONE" },
  TabLineSel = { fg = colors.fg, bg = "NONE", bold = true },
  Title = { fg = colors.primary, bold = true },
  Visual = { bg = colors.bg_light },
  VisualNOS = { bg = colors.bg_light },
  WarningMsg = { fg = colors.tertiary },
  WildMenu = { fg = colors.bg, bg = colors.primary },

  ["@variable"] = { fg = colors.fg },
  ["@property"] = { fg = colors.fg_dark },
  ["@field"] = { fg = colors.fg_dark },
  ["@parameter"] = { fg = colors.tertiary },
  ["@function"] = { fg = colors.primary },
  ["@function.builtin"] = { fg = colors.secondary },
  ["@keyword"] = { fg = colors.primary, bold = true },
  ["@type"] = { fg = colors.tertiary },
  ["@type.builtin"] = { fg = colors.secondary },
  ["@string"] = { fg = colors.secondary },
  ["@number"] = { fg = colors.tertiary },
  ["@boolean"] = { fg = colors.tertiary },
  ["@constant"] = { fg = colors.tertiary },
  ["@comment"] = { fg = colors.outline, italic = true },

  TelescopeBorder = { fg = colors.outline },
  TelescopePromptBorder = { fg = colors.primary },
  TelescopePromptTitle = { fg = colors.bg, bg = colors.primary, bold = true },
  TelescopeSelection = { bg = colors.bg_light },
  NeoTreeNormal = { fg = colors.fg_dark, bg = "NONE" },
  NeoTreeNormalNC = { fg = colors.fg_dark, bg = "NONE" },
}

for group, opts in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, opts)
end
