require("colors.colors")
require("modules/monitors")
require("modules/autostart")
require("modules/look_and_feel")
require("modules/input")
require("modules/bindings")
require("modules/rules")

hl.env("XCURSOR_SIZE", "32")
hl.env("HYPRCURSOR_SIZE", "32")
hl.env("HYPRCURSOR_THEME", "AfterglowDynamic_B")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("GTK_THEME", "Adwaita:dark")
hl.env("COLORSCHEME", "prefer-dark")
hl.env("WEBKIT_DISABLE_COMPOSITING_MODE", 1)
hl.env("WEBKIT_DISABLE_DMABUF_RENDERER", 1)
