hl.on("hyprland.start", function ()
    hl.exec_cmd("$HOME/.config/wallpaper_loop.sh &")
    hl.exec_cmd("waybar &")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &")
    hl.exec_cmd("wl-paste --watch cliphist store &")
    hl.exec_cmd("wl-paste --type image --watch cliphist store &")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XCURSOR_THEME XCURSOR_SIZE HYPRCURSOR_THEME HYPRCURSOR_SIZE=Hyprland")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XCURSOR_THEME XCURSOR_SIZE HYPRCURSOR_THEME HYPRCURSOR_SIZE")
    hl.exec_cmd("~/.config/hypr/scripts/xdg-portal-init.sh &")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'")
    hl.exec_cmd("hyprctl keyword windowrulev2 \"blur,class:^(dev.zed.Zed)$\"")
    hl.exec_cmd("hyprctl keyword windowrulev2 \"blur,class:^(code-oss)$\"")
    hl.exec_cmd("hyprctl keyword windowrulev2 \"blur,class:^(thunar)$\"")
end)

