$image = /tmp/current_wallpaper.jpg

$background = rgba(121316ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(303033ff)

$inverse_primary = rgba(4a5f80ff)

$inverse_surface = rgba(e3e2e5ff)

$on_background = rgba(e3e2e5ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(1b314fff)

$on_primary_container = rgba(e2ebffff)

$on_primary_fixed = rgba(021c39ff)

$on_primary_fixed_variant = rgba(324767ff)

$on_secondary = rgba(29313eff)

$on_secondary_container = rgba(d9e0f1ff)

$on_secondary_fixed = rgba(141c28ff)

$on_secondary_fixed_variant = rgba(3f4755ff)

$on_surface = rgba(e3e2e5ff)

$on_surface_variant = rgba(c4c6ceff)

$on_tertiary = rgba(412d00ff)

$on_tertiary_container = rgba(ffe7c3ff)

$on_tertiary_fixed = rgba(271900ff)

$on_tertiary_fixed_variant = rgba(5a4313ff)

$outline = rgba(8e9198ff)

$outline_variant = rgba(44474eff)

$primary = rgba(b2c8edff)

$primary_container = rgba(394e6eff)

$primary_fixed = rgba(d5e3ffff)

$primary_fixed_dim = rgba(b2c8edff)

$scrim = rgba(000000ff)

$secondary = rgba(bfc7d7ff)

$secondary_container = rgba(3f4755ff)

$secondary_fixed = rgba(dbe3f4ff)

$secondary_fixed_dim = rgba(bfc7d7ff)

$shadow = rgba(000000ff)

$source_color = rgba(394e6eff)

$surface = rgba(121316ff)

$surface_bright = rgba(38393cff)

$surface_container = rgba(1f2022ff)

$surface_container_high = rgba(292a2cff)

$surface_container_highest = rgba(343537ff)

$surface_container_low = rgba(1b1b1eff)

$surface_container_lowest = rgba(0d0e10ff)

$surface_dim = rgba(121316ff)

$surface_tint = rgba(b2c8edff)

$surface_variant = rgba(44474eff)

$tertiary = rgba(e4c286ff)

$tertiary_container = rgba(614919ff)

$tertiary_fixed = rgba(ffdea7ff)

$tertiary_fixed_dim = rgba(e4c286ff)

