$image = /home/spancito/.config/wallpapers/Pictures/Wallpapers/rick.jpg

$background = rgba(101412ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2d312fff)

$inverse_primary = rgba(006c52ff)

$inverse_surface = rgba(dfe4dfff)

$on_background = rgba(dfe4dfff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(003829ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(002117ff)

$on_primary_fixed_variant = rgba(00513dff)

$on_secondary = rgba(16362bff)

$on_secondary_container = rgba(c4e8d8ff)

$on_secondary_fixed = rgba(002117ff)

$on_secondary_fixed_variant = rgba(2d4d41ff)

$on_surface = rgba(dfe4dfff)

$on_surface_variant = rgba(bdc9c2ff)

$on_tertiary = rgba(5a1b17ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(3d0605ff)

$on_tertiary_fixed_variant = rgba(77312bff)

$outline = rgba(88938dff)

$outline_variant = rgba(3e4944ff)

$primary = rgba(7ed8b7ff)

$primary_container = rgba(45a082ff)

$primary_fixed = rgba(9af4d2ff)

$primary_fixed_dim = rgba(7ed8b7ff)

$scrim = rgba(000000ff)

$secondary = rgba(abcebeff)

$secondary_container = rgba(2d4d41ff)

$secondary_fixed = rgba(c7ebdaff)

$secondary_fixed_dim = rgba(abcebeff)

$shadow = rgba(000000ff)

$source_color = rgba(449f81ff)

$surface = rgba(101412ff)

$surface_bright = rgba(353a38ff)

$surface_container = rgba(1c211eff)

$surface_container_high = rgba(262b29ff)

$surface_container_highest = rgba(313633ff)

$surface_container_low = rgba(181d1aff)

$surface_container_lowest = rgba(0b0f0dff)

$surface_dim = rgba(101412ff)

$surface_tint = rgba(7ed8b7ff)

$surface_variant = rgba(3e4944ff)

$tertiary = rgba(ffb4abff)

$tertiary_container = rgba(d1786fff)

$tertiary_fixed = rgba(ffdad6ff)

$tertiary_fixed_dim = rgba(ffb4abff)

