$image = /home/spancito/.config/wallpapers/Pictures/Wallpapers/wave.jpg

$background = rgba(1e100bff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(3d2d27ff)

$inverse_primary = rgba(aa3600ff)

$inverse_surface = rgba(f9ddd4ff)

$on_background = rgba(f9ddd4ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(5c1900ff)

$on_primary_container = rgba(ffdbcfff)

$on_primary_fixed = rgba(390c00ff)

$on_primary_fixed_variant = rgba(822700ff)

$on_secondary = rgba(49290eff)

$on_secondary_container = rgba(ffdcc5ff)

$on_secondary_fixed = rgba(301400ff)

$on_secondary_fixed_variant = rgba(633e22ff)

$on_surface = rgba(f9ddd4ff)

$on_surface_variant = rgba(dcc1b8ff)

$on_tertiary = rgba(462b00ff)

$on_tertiary_container = rgba(ffddb5ff)

$on_tertiary_fixed = rgba(2a1800ff)

$on_tertiary_fixed_variant = rgba(633f05ff)

$outline = rgba(a38c84ff)

$outline_variant = rgba(55433cff)

$primary = rgba(ffb59cff)

$primary_container = rgba(822700ff)

$primary_fixed = rgba(ffdbcfff)

$primary_fixed_dim = rgba(ffb59cff)

$scrim = rgba(000000ff)

$secondary = rgba(f1bc96ff)

$secondary_container = rgba(633e22ff)

$secondary_fixed = rgba(ffdcc5ff)

$secondary_fixed_dim = rgba(f1bc96ff)

$shadow = rgba(000000ff)

$source_color = rgba(a3796bff)

$surface = rgba(1e100bff)

$surface_bright = rgba(47352fff)

$surface_container = rgba(2b1c17ff)

$surface_container_high = rgba(362621ff)

$surface_container_highest = rgba(42312bff)

$surface_container_low = rgba(271813ff)

$surface_container_lowest = rgba(180b07ff)

$surface_dim = rgba(1e100bff)

$surface_tint = rgba(ffb59cff)

$surface_variant = rgba(55433cff)

$tertiary = rgba(f2bd7aff)

$tertiary_container = rgba(633f05ff)

$tertiary_fixed = rgba(ffddb5ff)

$tertiary_fixed_dim = rgba(f2bd7aff)

